import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'pathe'
import { afterAll, describe, expect, it } from 'vitest'
import { evmProvider } from '../src/chains/evm'
import { generateFromAbiViem } from '../src/chains/evm/codegen-viem'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(HERE, '..')
const ABI = resolve(REPO_ROOT, 'tests/frameworks/fixtures/evm/out/TestToken.sol/TestToken.json')

const workdirs: string[] = []
function makeOut(): string {
  const dir = mkdtempSync(join(tmpdir(), 'polyq-viem-'))
  workdirs.push(dir)
  return dir
}

describe('EVM viem codegen', () => {
  afterAll(() => {
    for (const dir of workdirs) rmSync(dir, { recursive: true, force: true })
  })

  it('emits an abi.ts with `as const satisfies Abi`', () => {
    const out = makeOut()
    generateFromAbiViem(ABI, out)
    const abiFile = readFileSync(join(out, 'test-token', 'abi.ts'), 'utf-8')
    expect(abiFile).toContain("import type { Abi } from 'viem'")
    expect(abiFile).toContain('as const satisfies Abi')
    expect(abiFile).toContain('TEST_TOKEN_ABI')
    expect(abiFile).toContain('export type TestTokenAbi')
  })

  it('emits a contract.ts with a getContract factory', () => {
    const out = makeOut()
    generateFromAbiViem(ABI, out)
    const contractFile = readFileSync(join(out, 'test-token', 'contract.ts'), 'utf-8')
    expect(contractFile).toContain("import { getContract } from 'viem'")
    expect(contractFile).toContain('createTestTokenContract')
    expect(contractFile).toContain('Address')
    expect(contractFile).toContain('TEST_TOKEN_ABI')
  })

  it('emits a barrel index.ts', () => {
    const out = makeOut()
    generateFromAbiViem(ABI, out)
    expect(existsSync(join(out, 'test-token', 'index.ts'))).toBe(true)
  })

  it('dispatches through the EVM provider when mode=viem', () => {
    const out = makeOut()
    evmProvider.generateClient(ABI, out, { mode: 'viem', outDir: out })
    expect(existsSync(join(out, 'test-token', 'abi.ts'))).toBe(true)
    const abiContent = readFileSync(join(out, 'test-token', 'abi.ts'), 'utf-8')
    expect(abiContent).toContain('as const satisfies Abi')
  })

  it('falls back to legacy codegen when mode is omitted', () => {
    const out = makeOut()
    evmProvider.generateClient(ABI, out, { outDir: out })
    // Legacy output uses 'contract.ts' with ABI const but no viem imports
    const legacy = readFileSync(join(out, 'test-token', 'contract.ts'), 'utf-8')
    expect(legacy).not.toContain('viem')
    expect(legacy).toContain('TEST_TOKEN_ABI')
  })

  it('honours codegen.license — custom SPDX string', () => {
    const out = makeOut()
    generateFromAbiViem(ABI, out, { outDir: out, license: 'Apache-2.0' })
    const abi = readFileSync(join(out, 'test-token', 'abi.ts'), 'utf-8')
    expect(abi.startsWith('// SPDX-License-Identifier: Apache-2.0')).toBe(true)
  })

  it('honours codegen.license === false — omits SPDX entirely', () => {
    const out = makeOut()
    generateFromAbiViem(ABI, out, { outDir: out, license: false })
    const abi = readFileSync(join(out, 'test-token', 'abi.ts'), 'utf-8')
    expect(abi).not.toContain('SPDX-License-Identifier')
    expect(abi.startsWith('// Auto-generated by Polyq')).toBe(true)
  })
})
