'use client'

import { useEffect, useState } from 'react'
import { Connection, PublicKey } from '@solana/web3.js'

// Generated by `polyq codegen` from target/idl/counter.json.
// Uncomment after running codegen for the first time.
// import { COUNTER_DISCRIMINATOR, deriveCounterPda } from '../generated/counter'

export default function Page() {
  const [slot, setSlot] = useState<number | null>(null)

  useEffect(() => {
    const conn = new Connection('http://127.0.0.1:8899')
    conn.getSlot().then(setSlot).catch(() => setSlot(-1))
  }, [])

  return (
    <main style={{ fontFamily: 'sans-serif', padding: 24 }}>
      <h1>Polyq starter</h1>
      <p>
        Validator slot:{' '}
        <code>
          {slot === null ? '…' : slot === -1 ? 'not running' : slot}
        </code>
      </p>
      <p>
        Run <code>polyq dev</code> in a second terminal to start the validator +
        deploy the counter program.
      </p>
    </main>
  )
}
